######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 24 16:15:44 2016
######################################################################

TEMPLATE = app
TARGET = thesis
DEPENDPATH += . inc
INCLUDEPATH += .
CONFIG += c++14

# Input
HEADERS += inc/colormod.hpp inc/stdafx.hpp
SOURCES += main.cpp
